### ISSUE TITLE
php setup.php --update taking long time, without progress output

### ISSUE THREAD

**Issue by mokraemer** [tine-groupware/tine#52] opened 2024-05-23 11:49 UTC
After the latest update, I ran
php setup.php --update

This is taking a long time, not indicating what is going on. I guess some kind of progress, e.g.
10 of 560000 or anything else could help.

**Comment by mokraemer** [comment] 2024-05-23 11:50
finally it stops with
"waited for Action Queue to become empty for more than 300 sec"

**Comment by mokraemer** [comment] 2024-05-24 08:10
thanks for your comment. The documentation is not very clear about the config and how to setup tine. Maybe I am missing sth.

I tried your command. It did not return, but after cancelling it, the setup worked.
Attaching my config, maybe I am missing sth relevant... 
[config.txt](https://github.com/tine-groupware/tine/files/15430030/config.txt)


Looking at [AdminQueue](https://tine-docu.s3web.rz1.metaways.net/operators/howto/tine20AdminQueue/), tried to execute
```
php tine20.php --method Tinebase.monitoringCheckQueue
QUEUE FAIL: Tinebase_Exception - state actionQueueLastDuration not set
```

finally this has no result:
`redis-cli --scan --pattern "*tine20worker*" `

Is it better to enable cron, and trigger the worker or should I prefer [Scheduler](https://tine-docu.s3web.rz1.metaways.net/operators/howto/tine20AdminScheduler/) "/usr/sbin/tine20-cli" - which I guess is sth. like php tine20.php (not documented anywhere)

**Comment by ignoreigor** [comment] 2024-05-24 09:13
> I tried your command. It did not return, but after cancelling it, the setup worked. Attaching my config, maybe I am missing sth relevant... [config.txt](https://github.com/tine-groupware/tine/files/15430030/config.txt)

There is no output, except logging, if activated. It works the queued tasks silently, like sending some mails. Normally it never ends.

worker != Tinebase.triggerAsyncEvents 
Best approach is to daemonize the worker, there were some hints in the packages. Personally I run the command with screen and detached the terminal, so that it survives my logout.

Worker was originally created to decouple long running tasks from UI, so that UI have to wait until task is queued instead of waiting until task has finished.

Additionally you should run a cron, that Tinebase.triggerAsyncEvents 

That is my output. 

```
sudo -u www-data php tine20.php --method Tinebase.monitoringCheckQueue
QUEUE OK | size=0;lrsize=0;lastJobId=0;lastDuration=0.001;lastDurationUpdate=50;
```
nearly configures as your, but added queueName (no idea why I did it)

  'actionqueue' =>
  array (
    'active' => true,
    'backend' => 'Redis',
    'host' => 'localhost',
    'port' => 6379,
    'queueName' => 'tine20worker',
  ),


> 
> Looking at [AdminQueue](https://tine-docu.s3web.rz1.metaways.net/operators/howto/tine20AdminQueue/), tried to execute
> 
> ```
> php tine20.php --method Tinebase.monitoringCheckQueue
> QUEUE FAIL: Tinebase_Exception - state actionQueueLastDuration not set
> ```
> 
> finally this has no result: `redis-cli --scan --pattern "*tine20worker*" `

This gave me some: tine20workerDeadLetter

Corrections, if something is explained wrong. Maybe a topic for one of the next podcad episodes.

**Comment by ignoreigor** [comment] 2024-05-24 10:47
I suppose there are no entries in your db when querying
select * from tine20_application_states where name like '%actionQueueLastDuration%';

But why?

**Comment by ignoreigor** [comment] 2024-05-24 11:08
Your crons, e.g. Tinebase.triggerAsyncEvents, are not working, while you have configured 
  'cron_disabled' => true,

Is there a reason to do so?

**Comment by mokraemer** [comment] 2024-05-24 13:58
I guess, I read it somewhere...
removed that line, but no change for the cron-job - same exception

**Comment by pschuele** [comment] 2024-06-17 11:31
see https://tine-docu.s3web.rz1.metaways.net/operators/howto/tine20AdminQueue/ for information about the worker + the --update error message "waited for Action Queue to become empty for more than 300 sec".
the queue needs to be emptied (or disabled) first before the update can commence.

is there still a problem here or can we close this issue?

**Comment by mokraemer** [comment] 2024-06-17 12:16
since queue did not want to get empty, I guess this problem still exists.
FYI: this is new. Never had this in years.

**Comment by pschuele** [comment] 2024-06-26 13:39
I would close this issue as setup.php works as intended. it looks more like a problem with the worker - we should open a new issue if that persists.

**Closed by pschuele** 2024-06-26 13:39 UTC
Labels: Setup, update
