### ISSUE TITLE
html-proxy isn't replaced 

### ISSUE THREAD

**Issue by ignoreigor** [tine-groupware/tine#34] opened 2024-03-28 15:30 UTC
Hi, 

having a look on 2024.12.x , I noticed one little thing: in addressbook's detail-pane or in calender-app when showing appointment details and attendees, some html-proxies aren't replaced in titles of contact's details or attendee information. Other contacts are shown correctly. 

`<em id="html-proxy-20000" class="html-proxy"></em> (some.mail@address.com)`

Addressbook:
![grafik](https://github.com/tine-groupware/tine/assets/8926991/830a38d6-0fc7-4c80-965b-24e4cd6e47a5)

Calendar:
![grafik](https://github.com/tine-groupware/tine/assets/8926991/492c4aaa-471f-4ad5-952a-ededa34b6e7f)

Looking for the difference between working an wrong contacts, I first thought it was caused by missing displaynames, but displaynames were always set and the entries are looking similar in the database. The crucial hint was not to look for something missing but something additional! Only contacts with mail addresses are affected. When mail addresses are displayed in these places, something seems so fail.

**Comment by ignoreigor** [comment] 2024-04-28 09:20
Still the same behaviour in [weekly-2024.17.1](https://github.com/tine-groupware/tine/releases/tag/weekly-2024.17.1)

**Comment by ignoreigor** [comment] 2024-06-01 09:25
There isn't any fixed in [weekly-2024.22.1](https://github.com/tine-groupware/tine/releases/tag/weekly-2024.22.1) for that issue.

**Comment by pschuele** [comment] 2024-06-18 14:28
hi, I can't reproduce this behaviour. it would be great if you could send me the json representation of one of the "broken" contacts / attendee.

**Comment by ignoreigor** [comment] 2024-06-19 11:48
> hi, I can't reproduce this behaviour. it would be great if you could send me the json representation of one of the "broken" contacts / attendee.

Hi, 

of course. Here is the json-object from Michael Mustermann, I edited some personal data in created_by manually. It was created with latest weekly-2024.24.1
[mustermann.json](https://github.com/user-attachments/files/15900038/mustermann.json)


![grafik](https://github.com/tine-groupware/tine/assets/8926991/9c41cf43-4c32-454b-838b-84d7979d7346)


Deleting the mail-address, i get the following json and contact is display correctly
[mustermann_ohne_mail.json](https://github.com/user-attachments/files/15900281/mustermann_ohne_mail.json)

**Comment by ignoreigor** [comment] 2024-07-04 13:29
I did some debugging, using Tinebase-3d8ac0412730ebd551d6-FAT.js

Problem is, in function replaceDomProxy(html)  
`const el = doc.getElementById(this.id);`
return null, in cases the proxy is not replaced.

That is affected by the replaced element, normally 
`<em id="html-proxy-1" class="html-proxy">`
,which is already html-encoded and no longer an element but 
`&lt;em id="html-proxy-1" class="html-proxy"&gt;&lt;/em&gt; `
when showing an email-address. So it can't be replaced and the html-source remains visible in frontend.

**Comment by pschuele** [comment] 2024-07-08 10:54
thanks for the debugging @ignoreigor 
@ccheng-dev can you have a look at this problem?

**Comment by pschuele** [comment] 2024-07-09 08:29
we are working on a fix, coming for 2024.11 and the weekly releases.

**Comment by pschuele** [comment] 2024-07-09 12:38
fixed with https://github.com/tine-groupware/tine/commit/aaf0c40ec3e0c5add9660092dced9f78e9859280

**Comment by ccheng-dev** [comment] 2024-07-09 12:38
here is the result after fix : 

![Screenshot from 2024-07-09 14-05-04](https://github.com/tine-groupware/tine/assets/61873678/622b148d-b8f2-4c86-bee6-3e783a290b99)

**Closed by pschuele** 2024-07-09 12:38 UTC
Labels: bug, Addressbook, Calendar

**Comment by ignoreigor** [comment] 2024-07-09 17:15
Looks great. Thank you for fixing. I'll have a look at the next weekly, as I am to lazy to build it myself.
